name: "[TWRP][berlna] Motorola Edge 2021"

on:
  workflow_dispatch:

env:
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: "Cleanup Environment"
         uses: rokibhasansagar/slimhub_actions@main

       - name: Initializing environment
         run: |
            echo "::group::Install Build Env Tool"
            sudo -E apt-get clean
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install curl libstdc++6 git wget repo rsync aria2
            echo "::endgroup::"
            git config --global user.name "Andrew Hexen"
            git config --global user.email "SyberHexen@gmail.com"   
            git clone https://github.com/akhilnarang/scripts --depth=1 --single-branch
            cd scripts
            echo "::group::Setup Build Env"
            sudo -E bash setup/android_build_env.sh
            echo "::endgroup::"
            echo "::group::Install Android Sdk"
            sudo -E bash setup/install_android_sdk.sh
            echo "::endgroup::"
             
       - name: "Sync & compile"
         run: |
            cd ~
            mkdir twrp
            cd twrp
            repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-12.1 --depth=1 --groups=all,-notdefault,-device,-darwin,-x86,-mips
            repo sync -j4
            cd build
            git fetch https://gerrit.twrp.me/android_build refs/changes/45/5445/1 && git cherry-pick FETCH_HEAD
            cd ~/twrp
            git clone https://github.com/SyberHexen/AnyKernel3 --depth=1 -b master+twrp bootable/recovery/installer
            git clone https://github.com/SyberHexen/android_device_motorola_berlna-twrp --depth=1 -b twrp-12.1 device/motorola/berlna
            . build/envsetup.sh && lunch twrp_berlna-eng && mka bootimage -j4

       - uses: actions/upload-artifact@v2
         with:
          name: recoveryzip
          path: work/out/target/product/*/*.zip

       - uses: actions/upload-artifact@v2
         with:
          name: recoveryimage
          path: work/out/target/product/*/*.img
